// ============================================
// UNRIVALED NETWORK — COMPLETE DATA LAYER
// ============================================

export const siteConfig = {
  name: 'Unrivaled Network',
  legalName: 'Unrivaled Network Corporation',
  tagline: 'AI-Powered Marketing. Unrivaled Results.',
  description: 'The only digital marketing agency that combines deep industry expertise with AI-powered advertising, answer engine optimization, and self-learning content systems to deliver 3-5x better ROI.',
  url: 'https://unrivalednetwork.com',
  email: 'info@unrivalednetwork.com',
  phone: '(951) 555-0123',
  address: {
    street: '3571 Verdugo Lane',
    city: 'Riverside',
    state: 'CA',
    zip: '92506',
    full: 'Riverside, CA 92506',
  },
  social: {
    linkedin: 'https://linkedin.com/company/unrivaled-network',
    instagram: 'https://instagram.com/unrivalednetwork',
    youtube: 'https://youtube.com/@unrivalednetwork',
    twitter: 'https://twitter.com/unrivalednet',
  },
  hours: {
    weekdays: '8:00 AM – 6:00 PM',
    saturday: '9:00 AM – 2:00 PM',
    sunday: 'Closed',
  },
};

export const industries = [
  {
    slug: 'home-services',
    name: 'Home Services',
    icon: '🏠',
    tagline: 'Dominate Emergency Searches & Seasonal Demand',
    description: 'From HVAC and plumbing to roofing and landscaping — we help home service businesses capture high-intent local searches and convert emergency calls into loyal customers.',
    color: '#22D3EE',
    heroStat: '450% avg lead increase',
    painPoints: [
      'Wasting budget on leads that never convert',
      'Invisible in "near me" and voice searches',
      'No-shows and last-minute cancellations',
      'Competing against national franchises with bigger budgets',
    ],
    solutions: [
      'Emergency service AEO optimization for instant visibility',
      'AI-powered lead qualification that reduces no-shows by 60%',
      'Seasonal campaign automation (HVAC peaks, storm damage, etc.)',
      'Hyper-local content strategy for neighborhood-level targeting',
    ],
    caseStudy: {
      client: 'SoCal HVAC & Plumbing Co.',
      before: '120 leads/month, 15% close rate',
      after: '540 leads/month, 38% close rate',
      timeframe: '90 days',
      roi: '12x return on ad spend',
    },
    keywords: ['emergency plumber near me', 'HVAC repair [city]', 'roofing contractor [city]', 'landscaping services near me'],
    services: ['seo-local-search', 'paid-advertising', 'reputation-management', 'marketing-automation', 'ai-answer-optimization'],
  },
  {
    slug: 'healthcare',
    name: 'Healthcare',
    icon: '🏥',
    tagline: 'Fill Appointment Books with High-Value Patients',
    description: 'HIPAA-compliant marketing strategies for dental, medical, and specialty practices that attract patients searching for treatments, not just general information.',
    color: '#818CF8',
    heroStat: '3x new patient volume',
    painPoints: [
      'Empty chairs during premium procedure slots',
      'Low-value insurance patients dominating the schedule',
      'HIPAA compliance making digital marketing feel risky',
      'Competitors outranking for high-value procedure searches',
    ],
    solutions: [
      'Treatment-focused AEO content that positions you as the authority',
      'HIPAA-compliant AI advertising targeting specific procedures',
      'Automated patient recall campaigns that fill cancellation gaps',
      'Reputation management that builds 5-star social proof at scale',
    ],
    caseStudy: {
      client: 'Pacific Dental Group',
      before: '18 new patients/month, 60% insurance',
      after: '54 new patients/month, 45% cash-pay',
      timeframe: '90 days',
      roi: '$420K additional annual revenue',
    },
    keywords: ['dental implants [city]', 'cosmetic dentist near me', 'Invisalign provider [city]', 'emergency dentist open now'],
    services: ['seo-local-search', 'ai-answer-optimization', 'reputation-management', 'content-marketing', 'paid-advertising'],
  },
  {
    slug: 'legal',
    name: 'Legal',
    icon: '⚖️',
    tagline: 'Win the Battle for High-Value Case Leads',
    description: 'Compete head-to-head with large firms using AI-powered case acquisition, authority content, and strategic visibility in AI-generated legal answers.',
    color: '#A78BFA',
    heroStat: '8x more qualified cases',
    painPoints: [
      'Pay-per-click costs exceeding $200/click for competitive keywords',
      'Lead quality declining while costs increase',
      'Large firms dominating AI search results',
      'Ethical advertising compliance adding complexity',
    ],
    solutions: [
      'Practice area authority content that earns AI citations',
      'AI-powered case valuation that prioritizes high-value matters',
      'Strategic AEO positioning for legal queries in ChatGPT/Perplexity',
      'Compliant reputation management across legal directories',
    ],
    caseStudy: {
      client: 'Inland Empire Personal Injury Firm',
      before: '25 leads/month, 3 qualified cases',
      after: '120 leads/month, 18 qualified cases',
      timeframe: '90 days',
      roi: '15x return (average case value $45K)',
    },
    keywords: ['personal injury lawyer [city]', 'car accident attorney near me', 'workers comp lawyer [city]', 'best DUI attorney [city]'],
    services: ['seo-local-search', 'paid-advertising', 'content-marketing', 'reputation-management', 'ai-answer-optimization'],
  },
  {
    slug: 'beauty-wellness',
    name: 'Beauty & Wellness',
    icon: '✨',
    tagline: 'Attract Premium Clients Who Book & Return',
    description: 'Fill your chairs and treatment rooms with clients who value quality over discount — using visual-first AI strategies and automated retention systems.',
    color: '#F472B6',
    heroStat: '2.5x average client value',
    painPoints: [
      'Relying on discount platforms that attract bargain hunters',
      'Inconsistent booking patterns creating revenue gaps',
      'Difficulty showcasing premium services visually',
      'High client churn without automated re-engagement',
    ],
    solutions: [
      'Visual AI advertising showcasing transformations and results',
      'Automated booking and re-engagement campaigns',
      'Premium service positioning that filters for high-value clients',
      'Influencer-style content strategy for social proof',
    ],
    caseStudy: {
      client: 'Luxe Med Spa & Aesthetics',
      before: '40% capacity, $180 avg ticket',
      after: '85% capacity, $420 avg ticket',
      timeframe: '60 days',
      roi: '9x return on marketing investment',
    },
    keywords: ['med spa [city]', 'Botox near me', 'facial treatment [city]', 'luxury salon [city]'],
    services: ['social-media', 'seo-local-search', 'paid-advertising', 'content-marketing', 'reputation-management'],
  },
  {
    slug: 'cleaning-services',
    name: 'Cleaning Services',
    icon: '🧹',
    tagline: 'Book Every Slot with Zero Manual Follow-Up',
    description: 'From residential cleaning to commercial janitorial — automate your booking pipeline and dominate local search with systems that work while you clean.',
    color: '#34D399',
    heroStat: '100% booking automation',
    painPoints: [
      'Manual scheduling consuming hours every week',
      'Price shoppers comparing you to the cheapest option',
      'Inconsistent lead flow creating feast-or-famine cycles',
      'No-show clients and last-minute cancellations',
    ],
    solutions: [
      'AI booking system that qualifies, prices, and schedules automatically',
      'Service-specific landing pages for each cleaning type',
      'Automated follow-up sequences that convert price shoppers',
      'Review generation system that builds trust at scale',
    ],
    caseStudy: {
      client: 'Premier Clean Co.',
      before: '60% booking rate, 20 hrs/week on phone',
      after: '92% booking rate, 2 hrs/week on phone',
      timeframe: '45 days',
      roi: '6x return plus 18 hours saved weekly',
    },
    keywords: ['house cleaning [city]', 'deep cleaning service near me', 'move out cleaning [city]', 'office cleaning services'],
    services: ['seo-local-search', 'paid-advertising', 'marketing-automation', 'reputation-management', 'conversion-optimization'],
  },
  {
    slug: 'pet-care',
    name: 'Pet Care',
    icon: '🐾',
    tagline: 'Fill Every Kennel, Grooming Slot & Vet Appointment',
    description: 'Pet parents search with emotion and urgency. We help you capture those moments with AI-powered visibility that keeps your services fully booked.',
    color: '#FBBF24',
    heroStat: '3x repeat bookings',
    painPoints: [
      'Seasonal empty kennels during off-peak months',
      'Difficulty differentiating from franchise competitors',
      'Pet parents comparing prices without understanding value',
      'Lack of automated rebooking for grooming and wellness visits',
    ],
    solutions: [
      'Pet parent journey mapping with automated touchpoints',
      'Seasonal campaign automation for boarding and grooming peaks',
      'AI-optimized local listings with pet-specific keywords',
      'Loyalty and referral automation that drives repeat business',
    ],
    caseStudy: {
      client: 'Happy Tails Pet Resort',
      before: '55% kennel occupancy, 200 grooming appts/month',
      after: '88% occupancy, 480 grooming appts/month',
      timeframe: '90 days',
      roi: '7x return on marketing spend',
    },
    keywords: ['dog boarding [city]', 'pet grooming near me', 'doggy daycare [city]', 'veterinary clinic [city]'],
    services: ['seo-local-search', 'social-media', 'content-marketing', 'reputation-management', 'paid-advertising'],
  },
  {
    slug: 'event-planning',
    name: 'Event Planning',
    icon: '🎉',
    tagline: 'Book Premium Events Without the Chase',
    description: 'Stop chasing clients and start attracting them. AI-powered marketing that showcases your events, builds authority, and fills your calendar with premium bookings.',
    color: '#F97316',
    heroStat: '4x premium bookings',
    painPoints: [
      'Feast-or-famine booking cycles',
      'Competing on price instead of value',
      'Difficulty showcasing past events to new prospects',
      'Long sales cycles with high drop-off rates',
    ],
    solutions: [
      'Portfolio-driven AI advertising that showcases your best work',
      'Automated proposal and follow-up sequences',
      'Venue and vendor partnership content strategy',
      'Seasonal campaign automation for wedding/event peaks',
    ],
    caseStudy: {
      client: 'Elegant Occasions Planning',
      before: '8 events/quarter, $3,200 avg value',
      after: '22 events/quarter, $5,800 avg value',
      timeframe: '90 days',
      roi: '11x return on marketing investment',
    },
    keywords: ['wedding planner [city]', 'event coordinator near me', 'corporate event planning [city]', 'party planner [city]'],
    services: ['social-media', 'content-marketing', 'paid-advertising', 'seo-local-search', 'conversion-optimization'],
  },
  {
    slug: 'professional-services',
    name: 'Professional Services',
    icon: '💼',
    tagline: 'Build Authority That Converts Decision-Makers',
    description: 'For consultants, accountants, financial advisors, and B2B service providers — build thought leadership that attracts high-value clients through AI-powered authority positioning.',
    color: '#60A5FA',
    heroStat: '5x qualified leads',
    painPoints: [
      'Referrals drying up without a digital pipeline',
      'Competing against established firms with bigger brands',
      'Long sales cycles with multiple decision-makers',
      'Difficulty demonstrating ROI of professional services',
    ],
    solutions: [
      'Thought leadership content strategy that earns AI citations',
      'LinkedIn + AI advertising targeting decision-makers by title',
      'Case study and authority content that shortens sales cycles',
      'Automated nurture sequences for long B2B buying journeys',
    ],
    caseStudy: {
      client: 'Summit Business Advisors',
      before: '5 qualified leads/month, 3-month sales cycle',
      after: '25 qualified leads/month, 6-week sales cycle',
      timeframe: '90 days',
      roi: '8x return with $180K new MRR',
    },
    keywords: ['business consultant [city]', 'CPA firm [city]', 'financial advisor near me', 'IT managed services [city]'],
    services: ['seo-local-search', 'content-marketing', 'paid-advertising', 'ai-answer-optimization', 'marketing-automation'],
  },
];

export const services = [
  {
    slug: 'seo-local-search',
    name: 'SEO & Local Search Domination',
    shortName: 'SEO & Local',
    icon: '🔍',
    tagline: 'Own the Map Pack. Dominate "Near Me" Searches.',
    description: 'We combine technical SEO, local optimization, and AI search strategy to make your business the obvious choice — on Google, in AI answers, and everywhere your customers search.',
    color: '#22D3EE',
    deliverables: [
      'Complete technical SEO audit and implementation',
      'Google Business Profile optimization and management',
      'Local citation building (50+ directories)',
      'Schema markup for AI-ready structured data',
      'Monthly content strategy and production',
      'Competitor analysis and gap exploitation',
    ],
    metrics: [
      { label: 'Avg. Traffic Increase', value: '340%' },
      { label: 'Map Pack Placement', value: 'Top 3' },
      { label: 'Keyword Rankings', value: '50+' },
    ],
  },
  {
    slug: 'ai-answer-optimization',
    name: 'AI Answer Engine Optimization (AEO)',
    shortName: 'AEO',
    icon: '🤖',
    tagline: 'Be the Answer AI Gives.',
    description: 'When customers ask ChatGPT, Perplexity, or Google AI for recommendations, your business should be the answer. We optimize your digital presence to be cited, recommended, and featured in AI-generated responses.',
    color: '#818CF8',
    deliverables: [
      'AI search visibility audit and strategy',
      'Structured content designed for AI citation',
      'FAQ and conversational content optimization',
      'Entity authority building across knowledge bases',
      'AI-generated answer monitoring and optimization',
      'Competitive positioning in AI recommendations',
    ],
    metrics: [
      { label: 'AI Citation Rate', value: '85%' },
      { label: 'AI Visibility Score', value: '9.2/10' },
      { label: 'Featured Answers', value: '200+' },
    ],
  },
  {
    slug: 'paid-advertising',
    name: 'AI-Powered Paid Advertising',
    shortName: 'Paid Ads',
    icon: '📣',
    tagline: 'Smarter Spend. Higher Returns. Zero Waste.',
    description: 'Our AI-managed advertising platform optimizes your campaigns 24/7 across Google, Meta, and emerging platforms — eliminating waste and doubling down on what converts.',
    color: '#F472B6',
    deliverables: [
      'Multi-platform campaign setup and management',
      'AI-driven bid optimization and budget allocation',
      'Custom audience building and lookalike targeting',
      'Creative testing and performance optimization',
      'Landing page design and conversion optimization',
      'Weekly reporting with transparent ROAS tracking',
    ],
    metrics: [
      { label: 'Avg. ROAS', value: '8.2x' },
      { label: 'Cost Per Lead Reduction', value: '62%' },
      { label: 'Lead Quality Score', value: '94%' },
    ],
  },
  {
    slug: 'content-marketing',
    name: 'Content Marketing & Authority Building',
    shortName: 'Content',
    icon: '✍️',
    tagline: 'Content That Converts. Authority That Compounds.',
    description: 'Strategic content that positions you as the undisputed industry expert — built for humans and optimized for AI citation. Every piece drives traffic, builds trust, and generates leads.',
    color: '#34D399',
    deliverables: [
      'Content strategy aligned with buyer journey',
      'AI-optimized blog posts and pillar pages',
      'Video content strategy and production guidance',
      'Email nurture sequences and newsletter systems',
      'Social media content calendar and templates',
      'Content performance tracking and optimization',
    ],
    metrics: [
      { label: 'Organic Traffic Growth', value: '280%' },
      { label: 'Content Engagement', value: '4.2min avg' },
      { label: 'Lead Attribution', value: '35%' },
    ],
  },
  {
    slug: 'social-media',
    name: 'Social Media Strategy',
    shortName: 'Social',
    icon: '📱',
    tagline: 'Turn Followers into Customers.',
    description: 'Strategic social media management that builds community, drives engagement, and converts followers into paying customers — powered by AI content tools and data-driven posting.',
    color: '#FBBF24',
    deliverables: [
      'Platform-specific content strategy',
      'AI-assisted content creation and scheduling',
      'Community management and engagement',
      'Influencer partnership strategy',
      'Social commerce optimization',
      'Monthly analytics and strategy refinement',
    ],
    metrics: [
      { label: 'Follower Growth', value: '150%' },
      { label: 'Engagement Rate', value: '5.8%' },
      { label: 'Social Revenue', value: '+420%' },
    ],
  },
  {
    slug: 'conversion-optimization',
    name: 'Conversion Rate Optimization (CRO)',
    shortName: 'CRO',
    icon: '📊',
    tagline: 'Turn More Clicks into Customers.',
    description: 'Every visitor is a potential customer. Our AI-powered CRO system tests, learns, and optimizes your website experience to convert more traffic into leads and sales.',
    color: '#F97316',
    deliverables: [
      'Comprehensive conversion audit',
      'A/B testing strategy and implementation',
      'Landing page design and optimization',
      'User journey mapping and friction elimination',
      'Form and checkout optimization',
      'Heatmap analysis and behavioral insights',
    ],
    metrics: [
      { label: 'Conversion Lift', value: '185%' },
      { label: 'Bounce Rate Reduction', value: '-45%' },
      { label: 'Revenue Per Visitor', value: '+92%' },
    ],
  },
  {
    slug: 'reputation-management',
    name: 'Reputation & Review Management',
    shortName: 'Reputation',
    icon: '⭐',
    tagline: 'Build a 5-Star Reputation That Sells for You.',
    description: 'Automated review generation, intelligent response management, and strategic reputation positioning that turns your best customers into your most powerful marketing channel.',
    color: '#EC4899',
    deliverables: [
      'Review generation automation (email/SMS)',
      'AI-powered review response system',
      'Review monitoring across 50+ platforms',
      'Crisis management protocol and alerts',
      'Review widget integration for website',
      'Competitive reputation benchmarking',
    ],
    metrics: [
      { label: 'Review Volume Increase', value: '300%' },
      { label: 'Average Rating', value: '4.8★' },
      { label: 'Response Time', value: '<2 hours' },
    ],
  },
  {
    slug: 'marketing-automation',
    name: 'Marketing Automation & AI',
    shortName: 'Automation',
    icon: '⚙️',
    tagline: 'Systems That Work While You Sleep.',
    description: 'Intelligent marketing automation that nurtures leads, re-engages past customers, and scales your marketing without scaling your team — powered by self-learning AI.',
    color: '#60A5FA',
    deliverables: [
      'CRM setup and optimization',
      'Automated lead nurture sequences',
      'Customer re-engagement campaigns',
      'Appointment scheduling automation',
      'Review request automation',
      'Custom reporting dashboards',
    ],
    metrics: [
      { label: 'Lead Response Time', value: '<60 sec' },
      { label: 'Manual Tasks Eliminated', value: '80%' },
      { label: 'Customer Retention', value: '+45%' },
    ],
  },
];

export const results = [
  { metric: '2.4B+', label: 'Ad Impressions Managed', icon: '👁️' },
  { metric: '500+', label: 'Businesses Scaled', icon: '🚀' },
  { metric: '$85M+', label: 'Revenue Generated', icon: '💰' },
  { metric: '10X', label: 'Average Client ROI', icon: '📈' },
];

export const processSteps = [
  {
    number: '01',
    name: 'Discover',
    title: 'Deep-Dive Business Analysis',
    description: 'We audit your entire digital presence, analyze competitors, identify untapped opportunities, and map your ideal customer journey.',
    icon: '🔍',
  },
  {
    number: '02',
    name: 'Strategize',
    title: 'AI-Powered Strategy Design',
    description: 'We design a custom growth strategy leveraging our full AI stack — prioritized by ROI potential and aligned with your business goals.',
    icon: '🧠',
  },
  {
    number: '03',
    name: 'Execute',
    title: 'Rapid Multi-Channel Launch',
    description: 'We deploy across all channels simultaneously — SEO, AEO, ads, content, automation — with weekly optimization cycles.',
    icon: '⚡',
  },
  {
    number: '04',
    name: 'Scale',
    title: 'Continuous Optimization & Growth',
    description: 'Our AI systems learn and improve weekly. We scale what works, cut what doesn\'t, and continuously expand your market share.',
    icon: '🚀',
  },
];

export const testimonials = [
  {
    quote: "Unrivaled Network transformed our practice. We went from struggling to fill chairs to having a 3-week waitlist. Their AI-powered approach to dental marketing is unlike anything we've seen.",
    author: 'Dr. Sarah Chen',
    role: 'Owner',
    company: 'Pacific Dental Group',
    industry: 'Healthcare',
    rating: 5,
    result: '3x new patients in 90 days',
  },
  {
    quote: "Our lead quality went through the roof. We're getting 8x more qualified cases than before, and our cost per acquisition dropped by 60%. The ROI speaks for itself.",
    author: 'Michael Rodriguez',
    role: 'Managing Partner',
    company: 'Rodriguez & Associates',
    industry: 'Legal',
    rating: 5,
    result: '15x ROAS on case acquisition',
  },
  {
    quote: "They automated our entire booking pipeline. I went from spending 20 hours a week on the phone to about 2 hours. Our booking rate jumped from 60% to 92%.",
    author: 'Jessica Park',
    role: 'Founder',
    company: 'Premier Clean Co.',
    industry: 'Cleaning Services',
    rating: 5,
    result: '92% automated booking rate',
  },
  {
    quote: "The team at Unrivaled Network doesn't just run ads — they built an entire growth engine for our med spa. Revenue is up 240% and we're booking premium treatments consistently.",
    author: 'Dr. Amanda Lee',
    role: 'Medical Director',
    company: 'Luxe Med Spa',
    industry: 'Beauty & Wellness',
    rating: 5,
    result: '240% revenue increase',
  },
  {
    quote: "We went from invisible to dominating local search. Every time someone asks AI for an HVAC recommendation in our area, we're the answer. Game changer.",
    author: 'Tom Mitchell',
    role: 'Owner',
    company: 'Mitchell HVAC Solutions',
    industry: 'Home Services',
    rating: 5,
    result: '450% lead increase',
  },
];

export const faqs = [
  {
    question: 'What makes Unrivaled Network different from other marketing agencies?',
    answer: 'Three things: (1) We\'re the only agency combining AI-powered advertising with answer engine optimization and self-learning content systems. (2) We specialize in 8 specific service industries, so we already know your market. (3) Every strategy is powered by our AI agent swarm — meaning smarter targeting, faster optimization, and 3-5x better results than traditional approaches.',
  },
  {
    question: 'How quickly will I see results?',
    answer: 'Most clients see measurable improvement within 30 days — increased lead flow, better ad performance, higher search rankings. Significant results (3-5x lead volume, top 3 map pack placement) typically come within 60-90 days. SEO and AEO build compound returns over 6-12 months.',
  },
  {
    question: 'Do you require long-term contracts?',
    answer: 'No long-term contracts. We offer month-to-month engagement because we believe results should earn your continued business, not a contract. That said, most clients stay 12+ months because the ROI is clear and compounding.',
  },
  {
    question: 'What industries do you specialize in?',
    answer: 'We specialize in 8 service business verticals: Home Services (HVAC, plumbing, roofing), Healthcare (dental, medical, specialty), Legal (PI, family, criminal), Beauty & Wellness (salons, med spas), Cleaning Services, Pet Care, Event Planning, and Professional Services (consulting, accounting, financial).',
  },
  {
    question: 'What is Answer Engine Optimization (AEO)?',
    answer: 'AEO is optimizing your business to appear in AI-generated answers from ChatGPT, Perplexity, Google AI Overviews, and other AI search engines. When someone asks AI "best dentist in Riverside" or "emergency plumber near me," AEO ensures YOUR business is the recommendation. This is the next frontier of search — and we\'re one of the only agencies doing it.',
  },
  {
    question: 'How does AI-powered advertising work?',
    answer: 'Our AI advertising platform manages your campaigns 24/7 — optimizing bids, testing creative, adjusting audiences, and reallocating budget to the highest-performing channels in real-time. It processes millions of data points to find your ideal customers at the lowest possible cost. The result: 8x average ROAS and 62% lower cost per lead.',
  },
  {
    question: 'What is your pricing structure?',
    answer: 'We offer three tiers: Growth Accelerator ($2,500-4,000/mo) for businesses ready to scale, Market Dominator ($5,000-8,000/mo) for aggressive growth, and Enterprise Custom ($10,000+/mo) for multi-location operations. Each tier includes a custom strategy — no cookie-cutter packages. Book a free audit for exact pricing based on your market and goals.',
  },
];

export const pricingTiers = [
  {
    name: 'Growth Accelerator',
    range: '$2,500 – $4,000/mo',
    tagline: 'For businesses ready to scale',
    target: 'Ideal for $500K–$2M revenue',
    features: [
      'SEO & Local Search optimization',
      'AI-powered paid advertising (1-2 platforms)',
      'Content marketing (4 pieces/month)',
      'Review management automation',
      'Monthly reporting & strategy calls',
      'Dedicated account manager',
    ],
    featured: false,
  },
  {
    name: 'Market Dominator',
    range: '$5,000 – $8,000/mo',
    tagline: 'Aggressive growth, maximum impact',
    target: 'Ideal for $2M–$10M revenue',
    features: [
      'Everything in Growth Accelerator, plus:',
      'Full AEO (Answer Engine Optimization)',
      'AI advertising across all platforms',
      'Content marketing (12 pieces/month)',
      'Marketing automation & CRM',
      'CRO & landing page optimization',
      'Bi-weekly strategy calls',
      'Priority support',
    ],
    featured: true,
  },
  {
    name: 'Enterprise Custom',
    range: '$10,000+/mo',
    tagline: 'Multi-location & enterprise scale',
    target: 'Ideal for $10M+ revenue / multi-location',
    features: [
      'Everything in Market Dominator, plus:',
      'Multi-location management',
      'Custom AI model training',
      'Dedicated content team',
      'Executive reporting dashboard',
      'Weekly strategy calls',
      'White-glove onboarding',
      'Quarterly business reviews',
    ],
    featured: false,
  },
];

export const locations = [
  {
    city: 'Riverside',
    region: 'Inland Empire',
    description: 'Headquarters — serving the entire Inland Empire region including Corona, Moreno Valley, San Bernardino, and Ontario.',
    isHQ: true,
  },
  {
    city: 'Los Angeles',
    region: 'LA County',
    description: 'Serving Los Angeles, Pasadena, Glendale, Long Beach, and the greater LA metropolitan area.',
    isHQ: false,
  },
  {
    city: 'Orange County',
    region: 'OC',
    description: 'Serving Irvine, Anaheim, Santa Ana, Huntington Beach, and all Orange County communities.',
    isHQ: false,
  },
  {
    city: 'San Diego',
    region: 'San Diego County',
    description: 'Serving San Diego, Chula Vista, Oceanside, Carlsbad, and the greater San Diego region.',
    isHQ: false,
  },
  {
    city: 'Ventura County',
    region: 'Central Coast',
    description: 'Serving Oxnard, Ventura, Thousand Oaks, Camarillo, and surrounding communities.',
    isHQ: false,
  },
  {
    city: 'Santa Barbara',
    region: 'Central Coast',
    description: 'Serving Santa Barbara, Goleta, Carpinteria, Montecito, and the American Riviera.',
    isHQ: false,
  },
];
